# Generated by Django 5.2.1 on 2025-08-15 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('courses', '0001_initial'),
        ('support_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefeedback',
            name='course_name',
        ),
        migrations.AddField(
            model_name='coursefeedback',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentprofile'),
        ),
    ]
