# Generated by Django 5.2.1 on 2025-07-14 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('meetings', '0005_meeting_access_type_meeting_is_password_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetinginvite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meetinginvite',
            name='user',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='is_password_required',
            new_name='is_recorded',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='access_type',
        ),
        migrations.AddField(
            model_name='meeting',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='courses.course'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('instant', 'Instant Meeting'), ('scheduled', 'Scheduled Meeting'), ('lecture', 'Course Lecture')], default='instant', max_length=20),
        ),
        migrations.CreateModel(
            name='MeetingChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='meetings.meeting')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='meetings.meeting')),
            ],
        ),
        migrations.DeleteModel(
            name='JoinRequest',
        ),
        migrations.DeleteModel(
            name='MeetingInvite',
        ),
    ]
