# Generated by Django 5.2.1 on 2025-07-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_live_classes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='live_class_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
