# Generated by Django 5.2.1 on 2025-08-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_qualification_teacherprofile_headline_and_more'),
        ('courses', '0002_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentprofile'),
        ),
    ]
