# Generated by Django 5.2.1 on 2025-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified')], max_length=20, null=True),
        ),
    ]
