# Generated by Django 5.2.1 on 2025-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_studentprofile_email_teacherprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
