# Generated by Django 5.2.1 on 2025-08-12 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_teacherprofile_bio'),
        ('courses', '0002_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='qualification',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='experience_years',
            new_name='total_course_hours',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='year',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='average_course_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='career_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='certificates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='completed_courses_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_courses_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('student', 'Full-time Student'), ('employed', 'Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Looking for Opportunities'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_students', through='courses.Enrollment', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='language_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_learning_time',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='availability_schedule',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='average_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='average_response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='awards',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='certifications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='course_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='courses_created',
            field=models.ManyToManyField(related_name='instructors', to='courses.course'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='part_time', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='expertise_areas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='expertise_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert'), ('master', 'Master')], default='expert', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='github_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='languages_spoken',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='notification_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='preferred_teaching_methods',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='publications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='response_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='total_students_helped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='youtube_channel',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['education_level', 'graduation_year'], name='authenticat_educati_11e0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['employment_status'], name='authenticat_employm_f92183_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['expertise_level', 'years_of_experience'], name='authenticat_experti_c1bb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['average_rating'], name='authenticat_average_1177eb_idx'),
        ),
    ]
