# Generated by Django 5.2.1 on 2025-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_qualification_teacherprofile_headline_and_more'),
        ('courses', '0003_alter_enrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='degree_certificates',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/degrees/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/id_proofs/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/resumes/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('subadmin', 'SubAdmin')], default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['status'], name='authenticat_status_159934_idx'),
        ),
    ]
