# Generated by Django 5.2.1 on 2025-08-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('video_upload', 'New Video Uploaded'), ('quiz_created', 'New Quiz Created'), ('student_enrolled', 'Student Enrolled'), ('live_class_scheduled', 'Live Class Scheduled'), ('payment_completed', 'Payment Completed'), ('meeting_start', 'Meeting Start'), ('general', 'General Notification')], max_length=30),
        ),
    ]
